# ███████╗███╗░░░███╗░██████╗██╗░░░██╗██████╗░░██████╗░█████╗░██████╗░██╗██████╗░███████╗
# ██╔════╝████╗░████║██╔════╝██║░░░██║██╔══██╗██╔════╝██╔══██╗██╔══██╗██║██╔══██╗██╔════╝
# █████╗░░██╔████╔██║╚█████╗░██║░░░██║██████╦╝╚█████╗░██║░░╚═╝██████╔╝██║██████╦╝█████╗░░
# ██╔══╝░░██║╚██╔╝██║░╚═══██╗██║░░░██║██╔══██╗░╚═══██╗██║░░██╗██╔══██╗██║██╔══██╗██╔══╝░░
# ██║░░░░░██║░╚═╝░██║██████╔╝╚██████╔╝██████╦╝██████╔╝╚█████╔╝██║░░██║██║██████╦╝███████╗
# ╚═╝░░░░░╚═╝░░░░░╚═╝╚═════╝░░╚═════╝░╚═════╝░╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝╚═════╝░╚══════╝
# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
settings:
  symbol: "&6&l+ &7" # Настройка символа, который будет писаться после доната игрока. В конце поставьте пробел и цветовой код, чтобы никнейм игрока с подпиской отображался корректно
  prefix-1: "%prefix%%symbol%" # Префикс игрока с подпиской
  prefix-2: "%prefix% &7" # Префикс игрока без подписки
  commands-on-give: # Команды при выдаче подписки
    - "p give %player% 1000"
    - "lp user %player% permission set essetials.god"
  commands-on-take: # Команды при снятии подписки
    - "lp user %player% permission unset essetials.god"
placeholders:
  has:
    yes-sub: "&aДа" # Когда есть подписка у игрока
    no-sub: "&cНет" # Когда нет подписки у игрока
messages:
  no-permission: "&fУ Вас &c&nнедостаточно&f &fправ!" # Сообщение, когда у игрока не хватает прав
  reload: "&fВы &aуспешно &fперезагрузили плагин!" # Сообщение, когда плагин перезагружен
  no-args: # Сообщение, когда не хватает аргументов
    - "&afmSubscribe &8| &fПомощь:"
    - ""
    - "&a/fmsubscribe give &8(&aигрок&8) &8(&aсрок&8) - &fвыдать игроку подписку"
    - "&a/fmsubscribe take &8(&aигрок&8) - &fснять игроку подписку"
    - "&a/fmsubscribe info &8(&aигрок&8) - &fузнать, есть ли у игрока подписка, или нет"
    - "&a/fmsubscribe reload &8- &fперезагрузить плагин"
  null-player: "&fИгрок не найден." # Сообщение, когда игрок не найден
  already-exists: "&fУ игрока уже есть подписка." # Сообщение, когда у игрока уже есть подписка
  no-exists: "&fУ игрока нет подписки!" # Сообщение, когда у игрока нет подписки
  give-duration: "&fВы выдали подписку игроку &6%player% &fна &a%duration%дн&7!" # Сообщение, когда вы выдали игроку подписку на время
  give-forever: "&fВы выдали подписку игроку &6%player% &fнавсегда&7!" # Сообщение, когда вы выдали игроку подписку навсегда
  take: "&fВы забрали подписку у игрока &6%player%&f!" # Сообщение, когда вы сняли у игрока подписку
  incorrect-date: "&fВы ввели некорректную дату!" # Сообщение, когда вы ввели некорректную дату
  no-sub: "&fУ игрока нет подписки!" # Сообщение, когда у игрока нет подписки
  yes-sub: "&fУ игрока есть подписка!" # Сообщение, когда у игрока есть подписка